name = "PolySeries"
uuid = "6f3fcde8-8165-4326-91a7-f7698485e8a3"
version = "0.1.0"
authors = ["Yue Hao <haoyue@msu.edu>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[extensions]
PolySeriesEnzymeExt = "Enzyme"

[compat]
Enzyme = "0.13"
StaticArrays = "1"
Test = "1"
julia = "1.9"
